package model.regulators;

/**
 * This interface represents a regulator, which defines methods for controlling and providing input to a regulatory
 * gene.
 */
public interface Regulator {

  /**
   * Compute and provide an input value for a regulatory gene.
   *
   * @return The input value generated by the regulator.
   */
  double inputFunction();

  /**
   * Get a description of this regulator.
   *
   * @return A string describing the regulator.
   */
  public String description();
}

